# This is a basic workflow to help you get started with Actions

name: TestCI
env:
  TESTRAIL_USER: hao.xu@intel.com
  TESTRAIL_TOKEN: Temp111


# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: cache-pip-linux
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ubuntu-latest-pip-3.7
        restore-keys: |
          ubuntu-latest-pip-3.7
    - name : install tool3
      run: sudo apt install python3-pip python3-setuptools python3-tk python3-wheel xz-utils file
      shell : bash

    # Runs a single command using the runners shell
    - name: download uploading TestRail script
      run: |
        echo Hello, world!
        cd ~
        echo "============clone the Resp======================"
        git clone https://github.com/zephyrproject-rtos/qm.git
        echo "================================================"
        ls -lrt ~/qm/scripts/test_reports
        cd ~/qm/scripts/test_reports
        echo "=======install python requirements=============="
        pip3 install --user -r requirements.txt
        echo "================================================"
        
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        pwd    
        sh -x script/upload.sh
        ls -lrt ~/qm/scripts/test_reports/junit4TestRail/
       
